### PR TITLE
Support for Shipper Release Indicator

### PR DESCRIPTION
**Pull request by n8man**
Update README.md to show how to set shipper release indicator

### CODE REVIEW

**Comment by gabrielbull** [comment]
@n8man Hi, thanks for your efforts. I am no longer maintaining this project and from the looks of it, there is not much activity. If you want to merge you PR, I'd be happy to add you as a contributor. Thanks.

**Comment by n8man** [comment]
Yes, please merge.

Thanks!

**Comment by n8man** [comment]
Sorry, I hadn't realized this has any quality failures. I just fixed it.

**Comment by n8man** [comment]
Hey @gabrielbull, can you or @scottcwilson merge this?

Thanks!

**Comment by gabrielbull** [comment]
@n8man Added you as collaborator. If you want access to the packagist config let me know by email.

**Pull request merged**
