### PR TITLE
Log XML requests / responses to log files

### PR DESCRIPTION
**Pull request by stefandoorn**
While implementing the Rate API I had to figure out at some moments what was send as XML and what was returned. Ofcourse you can temporary put some var_dumps, but it was helping me to have the request & response together with the same filename prefix in a logs directory. I wouldn't advise on using this in production, although it can help debugging problems.

For now I generated a LogInterface with 2 functions and a LogFile class. It makes it easy to add other ways of logging, eg LogDatabase, LogRedis, LogMemcache, whatever. 

It's a first version quickly created to support my use case and I think I applied the change everywhere necessary, but let me know if I'm missing things so I can adjust them.

Besides that, I'm not sure whether you like this feature implemented or not, if not feel free to reject it ofcourse.

### CODE REVIEW

**Comment by gabrielbull** [comment]
This is not passing the unit tests?

**Comment by stefandoorn** [comment]
True. Am willing to adjust it, but first would like to know whether you like the idea of implementing it. If not, I'll keep it for my local development only.

**Comment by gabrielbull** [comment]
Well, personally I think it should implement [PSR3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md). Then yes, I would agree this is a good idea.

**Comment by stefandoorn** [comment]
Perfect, makes sense. Haven't implemented it with PSR3 yet, so have to dive into it. Hope to find some time soon to have a look at it. For now I'll close it.

**Pull request closed without merging**
