### PR TITLE
Add LabelDelivery to ShipmentServiceOptions

### LINKED ISSUE #116: How to set ShipmentServiceOptions for email delivery
First off, thank you very much for this project. It has been hugely helpful.

I'm wondering how I can achieve adding `<ShipmentServiceOptions/>` to the request XML?

Per UPS, the following XML needs to be added to the request in addition to setting the returnService code to 8 (ReturnService::ELECTRONIC_RETURN_LABEL_ERL):

```
   <ShipmentServiceOptions>

     <LabelDelivery>

       <LabelLinksIndicator/>

       <EMail>

         <EMailAddress>emailaddress@email.com</EMailAddress>

         <FromEMailAddress>emailaddress@email.com</FromEMailAddress>

         <FromName>From Name</FromName>

         <Memo/>

         <Subject>Subject</Subject>

       </EMail>

     </LabelDelivery>

   </ShipmentServiceOptions>
```

There is a `\UPS\Entity\ShipmentServiceOptions` class, but it doesn't appear that I can do what I'm looking for without modifying the class. 

Do you have any suggestions? Thanks in advance for any help you can provide.

### PR DESCRIPTION
**Pull request by scottsb**
Adds ability to have UPS send email with return label.

Co-authored-by: David Richter <drichter@ripen.com>

Fixes #116

### CODE REVIEW

**Comment by scottsb** [comment]
I'm not sure why the HHVM test on Travis is failing, but the involved isn't related to this PR.

**Comment by scottcwilson** [comment]
@scottsb  I have the same issue with my PR - I think it's an (unrelated) issue with the test.

**Comment by scottcwilson** [comment]
@scottsb Please rebase your branch - I have made hhvm an acceptable failure for now.

**Comment by scottsb** [comment]
Rebased; checks now passing.

**Pull request merged**
