### PR TITLE
Fix issue 63

### PR DESCRIPTION
**Pull request by rafacuest**
Changes sugested #63

### CODE REVIEW

**Comment by stefandoorn** [comment]
The test still fail. If you click on Details behind the travis-ci line, you can see per PHP version what the error is. Something with an undefined index as far as I can see for now.

**Comment by stefandoorn** [comment]
@rafacuest I believe the error comes from:

````
private $ReferenceNumber;
````

While later in the code you reference it as $this->referenceNumber (note the capital, lowercase). Could you adjust this to be the camel case version ($referenceNumber)?

**Comment by rafacuest** [comment]
:) Thanks! In the future i promise i'll use the test in Local

**Comment by stefandoorn** [comment]
Looks good :) Only thing is what we need now are:
* Test for the new request (I can make that if you want)
* Documentation (in the README.md file) describing the new feature

**Comment by rafacuest** [comment]
@stefandoorn I would prefer than some other make the test because I didn't made this before. :(

**Pull request merged**
