### PR TITLE
Adds support for a second reference number

### PR DESCRIPTION
**Pull request by hm122**
The UPS API allows to set two different reference numbers for a shipment. This functionality is added with this pull request.

### CODE REVIEW

**Comment by stefandoorn** [comment]
Unfortunately this is a breaking change, as e.g. my current implementation will break. I'm using the 'setReferenceNumber' function to insert a ReferenceNumber object. Can we maybe find a workaround to introduce the same functionality, without making it breaking? E.g. what's the maximum amount of reference numbers? If not so many we can think of adding a setReferenceNumber2, etc. In any case there should be validation on the amount also, so if not too much this might be a nice workaround to get the same feature without breaking.

**Comment by hm122** [comment]
True. The maximum number of reference numbers is two. I will adjust this as suggested.

**Comment by hm122** [comment]
In principle this could be fixed by re-adding the original setReferenceNumber method. Is that fine? Or would you prefer a setReferenceNumber2 method?

**Comment by stefandoorn** [comment]
Two options I think:
* setReferenceNumber takes an array or one object, and parses that one as required into an array or just keeps the array.
* or revert part of the change and add the second method.

My preference goes for the latter as it allows for proper type hinting, which is more strict in using the code.

**Comment by hm122** [comment]
Alright, I will make a new pull request :)

**Comment by hm122** [comment]
I adjusted the code, should be working now.

**Comment by stefandoorn** [comment]
Looks good. Could you (if possible) change also the CHANGELOG file to reflect this feature for release 0.7.1? Then I will merge it and bring out the new release.

**Comment by hm122** [comment]
Great, thanks! The changelog is now up to date!

**Pull request merged**
